name: Release otelcol-main

on:
  release:
    types: [published]

jobs:
  release:
    name: Release otelcol-main
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-main
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "amd64", "arm64" ]'
    secrets: inherit
    permissions: write-all
